# -*- coding: utf-8 -*-
"""Product_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ligqdhCdXkCOOHjJdevKX2MP3x6EiIld
"""

class Product:
  def __init__(self,id,name,price,rating):
    self.id=id
    self.name=name
    self.price=price
    self.rating=rating
class User:
  def __init__(self):
    self.products=[]

  #add product
  def add_product(self):
    id=int(input("Enter product id: "))
    for p in self.products:
      if p.id==id:
        print("Product already exists")
        return
    name=input("Enter product name: ")
    price=int(input("Enter product price: "))
    rating =float(input("Enter product rating: "))
    self.products.append(Product(id,name,price,rating))
    print("Product added successfully")

  #delete product
  def delete_product(self):
    if not self.products:
      print("No products to delete")
      return
    id =int(input("Enter product id: "))
    for p in self.products:
      if p.id==id:
        self.products.remove(p)
        print("Produt deleted successfully")
        return
    else:
      print("Product with this ID doesnt exists! Please enter a valid ID")

  # show produts or display all products
  def show_products(self):
    if not self.products:
      print("No products to display")
      return
    for p in self.products:
      print("|  ID  |  Name  |  Price |  Ratiing  |")
      print("-"*32)
      print(f"|  {p.id}  |  {p.name}  |  {p.price}  |  {p.rating}  |")

  # search for a product
  def search_product(self):
    if not self.products:
      print("No products to search")
      return
    id =int(input("Enter product id: "))
    for p in self.products:
      if p.id==id:
        print("|  ID  |  Name  |  Price |  Rating  |")
        print("-"*32)
        print(f"|  {p.id}  |  {p.name}  |  {p.price}  |  {p.rating}  |")
        return
    else:
      print("Product not found!Please enter a valid product id")

  #sort prices
  def sort_price(self):
    if not self.products:
      print("No products to sort price")
      return
    self.products.sort(key=lambda product:product.price)
    print("Prices are sorted from low to high!")
    self.show_products()


  #sort ratings
  def sort_rating(self):
    if not self.products:
      print("No products to sort ratings")
      return
    self.products.sort(key=lambda product:product.rating,reverse=True)
    print("Ratings are sorted from high to low!")
    self.show_products()

 # create user object
user=User()

print("<--------------Welcome to Product Management System--------------->")
while True:
    print("1->Add Product")
    print("2->Delete Product")
    print("3->Show Product")
    print("4->Search Product")
    print("5->Sort Product Prices")
    print("6->Sort Product Ratings")
    print("7->Exit the application")

    #Take choice from the user
    choice=int(input("Enter your choice: "))

    match choice:
      case 1:user.add_product()
      case 2:user.delete_product()
      case 3:user.show_products()
      case 4:user.search_product()
      case 5:user.sort_price()
      case 6:user.sort_rating()
      case 7:
        print("Thank you!Have a nice day!Visit Again")
        break
      case _:
        print("Invalid Choice!Please Try again!")